# local build uses nginx and gunicorn
version: '3'
services:
  web:
    build:
      context: ./NovskyProject
    environment:
      - SECRET_KEY=testkey
      - PG_PASSWORD
      - PG_URL
      - DJANGO_ENV=PROD
    ports:
      - '4005:8000'
