# local build uses nginx and gunicorn
version: '3'
services:
  web:
    build:
      context: ./NovskyProject
    environment:
      - SECRET_KEY=testkey
      - PG_PASSWORD
      - PG_URL
  nginx:
    depends_on:
      - web
    build:
      context: ./nginx
    ports:
      - '4005:80'
