# local build uses django dev server
# should be able to run this in any environment
version: '3'
services:
  tests:
    build:
      context: ./NovskyProject
      dockerfile: Dockerfile.dev
    volumes:
      - ./NovskyProject:/django_project
    environment:
      - SECRET_KEY=testkey
      - DJANGO_ENV=DEV
    command: ["python", "manage.py", "test", "-v", "1"]
