version: '3'
services:
  web:
    image: "novskytech/novskyproject"
    hostname: web
    environment:
      - DJANGO_ENV
      - SECRET_KEY
      - PG_PASSWORD
      - PG_URL
    ports:
      - '80:8000'
