# Generated by Django 4.1 on 2022-08-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Visual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visual_name", models.CharField(max_length=100)),
                ("visual_body", models.TextField()),
                ("description", models.TextField()),
                ("detail", models.CharField(max_length=300)),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
                ("tags", models.ManyToManyField(to="visuals.tag")),
            ],
        ),
    ]
