# Generated by Django 4.1 on 2022-08-22 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visuals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visual",
            name="tags",
            field=models.ManyToManyField(related_name="tag", to="visuals.tag"),
        ),
    ]
