# Generated by Django 4.0.5 on 2022-08-26 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("visuals", "0004_remove_visual_description_remove_visual_detail_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.URLField(max_length=100)),
                ("url", models.URLField(max_length=400)),
                ("description", models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name="visual",
            name="viz_type",
            field=models.CharField(default="foo", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="visual",
            name="body",
            field=models.TextField(help_text="should be javascript or html"),
        ),
        migrations.AddField(
            model_name="visual",
            name="resources",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resource",
                to="visuals.resource",
            ),
            preserve_default=False,
        ),
    ]
