# Generated by Django 4.1 on 2022-09-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visuals", "0010_visual_viz_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visual",
            name="viz_description",
            field=models.CharField(max_length=400, null=True),
        ),
    ]
