# Generated by Django 4.1 on 2022-09-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visuals", "0011_alter_visual_viz_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visual",
            name="viz_description",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
