# Generated by Django 4.1 on 2022-09-18 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visuals", "0012_alter_visual_viz_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visual",
            name="summary",
            field=models.TextField(
                blank=True, help_text="interesting commentary related to the viz"
            ),
        ),
        migrations.AlterField(
            model_name="visual",
            name="viz_description",
            field=models.CharField(
                blank=True,
                help_text="help explain the viz iteself, ie x axis represents ...",
                max_length=400,
                null=True,
            ),
        ),
    ]
